import json
import pytest
from cp_request import (
    Control,
    ExperimentalRequest, ExperimentEncoder, ExperimentDecoder,
    Measurement,
    NamedEntity,
    Sample,
    Treatment,
    Unit,
    Value,
    Version
)
from cp_request.design import (
    BlockReference,
    DesignBlock,
    GenerateBlock,
    ProductBlock,
    ReplicateBlock,
    SubjectReference,
    SumBlock,
    TreatmentReference,
    TupleBlock
)


class TestExperimentalRequest:

    def test_request(self):
        r1 = ExperimentalRequest(
            cp_name='NOVEL_CHASSIS',
            reference_name='NovelChassis-NAND-Ecoli-Titration',
            reference_url='https://docs.google.com/document/d/1oMC5VM3XcFn6zscxLKLUe4U-TXbBsz8H6OQwHal1h4g',
            version=Version(major=1, minor=0, patch=0),
            subjects=[
                NamedEntity(
                    name="MG1655_NAND_Circuit",
                    reference="https://hub.sd2e.org/user/sd2e/design/MG1655_NAND_Circuit/1"
                ),
                NamedEntity(
                    name="MG1655_empty_landing_pads",
                    reference="https://hub.sd2e.org/user/sd2e/design/MG1655_empty_landing_pads/1"
                )
            ],
            treatments=[
                Treatment.create_from(
                    name='temperature',
                    value=Value(
                        value=37.0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000027'))),
                Treatment.create_from(
                    name='media',
                    entity=NamedEntity(name="M9 Glucose CAA",
                                       reference="https://hub.sd2e.org/user/sd2e/design/M9_glucose_CAA/1")),
                Treatment.create_from(
                    name='IPTG',
                    entity=NamedEntity(
                        name='IPTG',
                        reference='https://hub.sd2e.org/user/sd2e/design/IPTG/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))
                    ]
                ),
                Treatment.create_from(
                    name='L-arabinose',
                    entity=NamedEntity(
                        name='L-arabinose',
                        reference='https://hub.sd2e.org/user/sd2e/design/Larabinose/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))
                    ]
                ),
                Treatment.create_from(
                    name='Kan',
                    entity=NamedEntity(
                        name='Kan',
                        reference='https://hub.sd2e.org/user/sd2e/design/Kan/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000274'))
                    ]
                )
            ],
            designs=[
                DesignBlock(
                    label='strains',
                    definition=SumBlock(block_list=[
                        TupleBlock(block_list=[
                            SubjectReference(
                                entity_name='MG1655_NAND_Circuit'),
                            TreatmentReference.create_from(
                                treatment_name='Kan')
                        ]),
                        SubjectReference(
                            entity_name='MG1655_empty_landing_pads')
                    ])
                ),
                DesignBlock(
                    label='temperature-media',
                    definition=TupleBlock(block_list=[
                        TreatmentReference.create_from(
                            treatment_name='temperature'),
                        TreatmentReference.create_from(treatment_name='media')
                    ])
                ),
                DesignBlock(
                    label='conditions',
                    definition=ProductBlock(block_list=[
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='IPTG',
                                attribute='concentration'),
                            values=[
                                Value(
                                    value=0,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=0.25,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=2.5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=25,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=250,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064'))
                            ]),
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='L-arabinose',
                                attribute='concentration'),
                            values=[
                                Value(
                                    value=0,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=50,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=500,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=5000,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=25000,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064'))
                            ]),
                    ])
                ),
                DesignBlock(
                    label='experiment',
                    definition=ProductBlock(block_list=[
                        ReplicateBlock(
                            count=4,
                            block=ProductBlock(block_list=[
                                BlockReference(label='strains'),
                                BlockReference(label='temperature-media'),
                                BlockReference(label='conditions')
                            ])
                        ),
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='timepoint'
                            ),
                            values=[
                                Value(
                                    value=5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=6.5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=8,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=18,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032'))
                            ]
                        ),
                    ])
                )
            ],
            measurements=[
                Measurement(
                    type='FLOW',
                    block=BlockReference(label='experiment'),
                    controls=[
                        Control(
                            name='positive_gfp',
                            sample=Sample(
                                subject=SubjectReference(
                                    entity_name='MG1655_NAND_Circuit'),
                                treatments=[
                                    TreatmentReference.create_from(treatment_name='timepoint', value=Value(
                                        value=18, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032'))),
                                    TreatmentReference.create_from(treatment_name='IPTG', attribute='concentration', value=Value(
                                        value=0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')))
                                ]
                            )
                        ),
                        Control(
                            name='negative_gfp',
                            sample=Sample(subject=SubjectReference(
                                entity_name='MG1655_empty_landing_pads'))
                        )
                    ],
                    performers=['Ginkgo']
                )
            ]
        )
        r2 = ExperimentalRequest(
            cp_name='NOVEL_CHASSIS',
            reference_name='NovelChassis-NAND-Ecoli-Titration',
            reference_url='https://docs.google.com/document/d/1oMC5VM3XcFn6zscxLKLUe4U-TXbBsz8H6OQwHal1h4g',
            version=Version(major=1, minor=0, patch=0),
            subjects=[
                NamedEntity(
                    name="MG1655_NAND_Circuit",
                    reference="https://hub.sd2e.org/user/sd2e/design/MG1655_NAND_Circuit/1"
                ),
                NamedEntity(
                    name="MG1655_empty_landing_pads",
                    reference="https://hub.sd2e.org/user/sd2e/design/MG1655_empty_landing_pads/1"
                )
            ],
            treatments=[
                Treatment.create_from(
                    name='temperature',
                    value=Value(
                        value=37.0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000027'))),
                Treatment.create_from(
                    name='media',
                    entity=NamedEntity(name="M9 Glucose CAA",
                                       reference="https://hub.sd2e.org/user/sd2e/design/M9_glucose_CAA/1")),
                Treatment.create_from(
                    name='IPTG',
                    entity=NamedEntity(
                        name='IPTG',
                        reference='https://hub.sd2e.org/user/sd2e/design/IPTG/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))
                    ]
                ),
                Treatment.create_from(
                    name='L-arabinose',
                    entity=NamedEntity(
                        name='L-arabinose',
                        reference='https://hub.sd2e.org/user/sd2e/design/Larabinose/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))
                    ]
                ),
                Treatment.create_from(
                    name='Kan',
                    entity=NamedEntity(
                        name='Kan',
                        reference='https://hub.sd2e.org/user/sd2e/design/Kan/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000274'))
                    ]
                )
            ],
            designs=[
                DesignBlock(
                    label='strains',
                    definition=SumBlock(block_list=[
                        TupleBlock(block_list=[
                            SubjectReference(
                                entity_name='MG1655_NAND_Circuit'),
                            TreatmentReference.create_from(
                                treatment_name='Kan')
                        ]),
                        SubjectReference(
                            entity_name='MG1655_empty_landing_pads')
                    ])
                ),
                DesignBlock(
                    label='temperature-media',
                    definition=TupleBlock(block_list=[
                        TreatmentReference.create_from(
                            treatment_name='temperature'),
                        TreatmentReference.create_from(treatment_name='media')
                    ])
                ),
                DesignBlock(
                    label='conditions',
                    definition=ProductBlock(block_list=[
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='IPTG',
                                attribute='concentration'),
                            values=[
                                Value(
                                    value=0,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=0.25,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=2.5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=25,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=250,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064'))
                            ]),
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='L-arabinose',
                                attribute='concentration'),
                            values=[
                                Value(
                                    value=0,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=50,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=500,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=5000,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=25000,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064'))
                            ]),
                    ])
                ),
                DesignBlock(
                    label='experiment',
                    definition=ProductBlock(block_list=[
                        ReplicateBlock(
                            count=4,
                            block=ProductBlock(block_list=[
                                BlockReference(label='strains'),
                                BlockReference(label='temperature-media'),
                                BlockReference(label='conditions')
                            ])
                        ),
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='timepoint'
                            ),
                            values=[
                                Value(
                                    value=5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=6.5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=8,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=18,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032'))
                            ]
                        ),
                    ])
                )
            ],
            measurements=[
                Measurement(
                    type='FLOW',
                    block=BlockReference(label='experiment'),
                    controls=[
                        Control(
                            name='positive_gfp',
                            sample=Sample(
                                subject=SubjectReference(
                                    entity_name='MG1655_NAND_Circuit'),
                                treatments=[
                                    TreatmentReference.create_from(treatment_name='timepoint', value=Value(
                                        value=18, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032'))),
                                    TreatmentReference.create_from(treatment_name='IPTG', attribute='concentration', value=Value(
                                        value=0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')))
                                ]
                            )
                        ),
                        Control(
                            name='negative_gfp',
                            sample=Sample(subject=SubjectReference(
                                entity_name='MG1655_empty_landing_pads'))
                        )
                    ],
                    performers=['Ginkgo']
                )
            ]
        )
        assert r1 == r1
        assert r1 == r2
        assert r1 != {}
        assert repr(r1) == "ExperimentalRequest(cp_name='NOVEL_CHASSIS', reference_name='NovelChassis-NAND-Ecoli-Titration', reference_url='https://docs.google.com/document/d/1oMC5VM3XcFn6zscxLKLUe4U-TXbBsz8H6OQwHal1h4g', version=Version(major=1, minor=0, patch=0), derived_from=None, subjects=[NamedEntity(name='MG1655_NAND_Circuit', reference='https://hub.sd2e.org/user/sd2e/design/MG1655_NAND_Circuit/1'), NamedEntity(name='MG1655_empty_landing_pads', reference='https://hub.sd2e.org/user/sd2e/design/MG1655_empty_landing_pads/1')], treatments=[SimpleTreatment(name='temperature', value=Value(value=37.0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000027'))), EntityTreatment(name='media', entity=NamedEntity(name='M9 Glucose CAA', reference='https://hub.sd2e.org/user/sd2e/design/M9_glucose_CAA/1')), EntityAttributeTreatment(name='IPTG', entity=NamedEntity(name='IPTG', reference='https://hub.sd2e.org/user/sd2e/design/IPTG/1'), attributes=[AttributeTreatment(name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))]), EntityAttributeTreatment(name='L-arabinose', entity=NamedEntity(name='L-arabinose', reference='https://hub.sd2e.org/user/sd2e/design/Larabinose/1'), attributes=[AttributeTreatment(name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))]), EntityAttributeTreatment(name='Kan', entity=NamedEntity(name='Kan', reference='https://hub.sd2e.org/user/sd2e/design/Kan/1'), attributes=[AttributeTreatment(name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000274'))])], designs=[DesignBlock(label='strains', definition=SumBlock(block_list=[TupleBlock(block_list=[SubjectReference(entity='MG1655_NAND_Circuit'), TreatmentReference(treatment_name='Kan')]), SubjectReference(entity='MG1655_empty_landing_pads')])), DesignBlock(label='temperature-media', definition=TupleBlock(block_list=[TreatmentReference(treatment_name='temperature'), TreatmentReference(treatment_name='media')])), DesignBlock(label='conditions', definition=ProductBlock(block_list=[GenerateBlock(treatment=TreatmentAttributeReference(treatment_name='IPTG', attribute='concentration'), values=[Value(value=0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=0.25, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=2.5, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=25, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=250, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))]), GenerateBlock(treatment=TreatmentAttributeReference(treatment_name='L-arabinose', attribute='concentration'), values=[Value(value=0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=5, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=50, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=500, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=5000, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')), Value(value=25000, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))])])), DesignBlock(label='experiment', definition=ProductBlock(block_list=[ReplicateBlock(count=4, block=ProductBlock(block_list=[BlockReference(label='strains'), BlockReference(label='temperature-media'), BlockReference(label='conditions')])), GenerateBlock(treatment=TreatmentReference(treatment_name='timepoint'), values=[Value(value=5, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032')), Value(value=6.5, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032')), Value(value=8, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032')), Value(value=18, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032'))])]))], measurements=[Measurement(type='FLOW', block=BlockReference(label='experiment'), controls=[Control(name='positive_gfp', sample=Sample(subject=SubjectReference(entity='MG1655_NAND_Circuit'), treatments=[TreatmentValueReference(treatment_name='timepoint', value=Value(value=18, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032'))), TreatmentAttributeValueReference(treatment_name='IPTG', attribute='concentration', value=Value(value=0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')))])), Control(name='negative_gfp', sample=Sample(subject=SubjectReference(entity='MG1655_empty_landing_pads'), treatments=[]))], performers=['Ginkgo'])])"

    def test_experiment_serialization(self):
        r1 = ExperimentalRequest(
            cp_name='NOVEL_CHASSIS',
            reference_name='NovelChassis-NAND-Ecoli-Titration',
            reference_url='https://docs.google.com/document/d/1oMC5VM3XcFn6zscxLKLUe4U-TXbBsz8H6OQwHal1h4g',
            version=Version(major=1, minor=0, patch=0),
            subjects=[
                NamedEntity(
                    name="MG1655_NAND_Circuit",
                    reference="https://hub.sd2e.org/user/sd2e/design/MG1655_NAND_Circuit/1"
                ),
                NamedEntity(
                    name="MG1655_empty_landing_pads",
                    reference="https://hub.sd2e.org/user/sd2e/design/MG1655_empty_landing_pads/1"
                )
            ],
            treatments=[
                Treatment.create_from(
                    name='temperature',
                    value=Value(
                        value=37.0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000027'))),
                Treatment.create_from(
                    name='media',
                    entity=NamedEntity(name="M9 Glucose CAA",
                                       reference="https://hub.sd2e.org/user/sd2e/design/M9_glucose_CAA/1")),
                Treatment.create_from(
                    name='IPTG',
                    entity=NamedEntity(
                        name='IPTG',
                        reference='https://hub.sd2e.org/user/sd2e/design/IPTG/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))
                    ]
                ),
                Treatment.create_from(
                    name='L-arabinose',
                    entity=NamedEntity(
                        name='L-arabinose',
                        reference='https://hub.sd2e.org/user/sd2e/design/Larabinose/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064'))
                    ]
                ),
                Treatment.create_from(
                    name='Kan',
                    entity=NamedEntity(
                        name='Kan',
                        reference='https://hub.sd2e.org/user/sd2e/design/Kan/1'
                    ),
                    attributes=[
                        Treatment.create_from(
                            name='concentration', unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000274'))
                    ]
                )
            ],
            designs=[
                DesignBlock(
                    label='strains',
                    definition=SumBlock(block_list=[
                        TupleBlock(block_list=[
                            SubjectReference(
                                entity_name='MG1655_NAND_Circuit'),
                            TreatmentReference.create_from(
                                treatment_name='Kan')
                        ]),
                        SubjectReference(
                            entity_name='MG1655_empty_landing_pads')
                    ])
                ),
                DesignBlock(
                    label='temperature-media',
                    definition=TupleBlock(block_list=[
                        TreatmentReference.create_from(
                            treatment_name='temperature'),
                        TreatmentReference.create_from(treatment_name='media')
                    ])
                ),
                DesignBlock(
                    label='conditions',
                    definition=ProductBlock(block_list=[
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='IPTG',
                                attribute='concentration'),
                            values=[
                                Value(
                                    value=0,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=0.25,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=2.5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=25,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=250,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064'))
                            ]),
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='L-arabinose',
                                attribute='concentration'),
                            values=[
                                Value(
                                    value=0,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=50,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=500,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=5000,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064')),
                                Value(
                                    value=25000,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000064'))
                            ]),
                    ])
                ),
                DesignBlock(
                    label='experiment',
                    definition=ProductBlock(block_list=[
                        ReplicateBlock(
                            count=4,
                            block=ProductBlock(block_list=[
                                BlockReference(label='strains'),
                                BlockReference(label='temperature-media'),
                                BlockReference(label='conditions')
                            ])
                        ),
                        GenerateBlock(
                            treatment=TreatmentReference.create_from(
                                treatment_name='timepoint'
                            ),
                            values=[
                                Value(
                                    value=5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=6.5,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=8,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032')),
                                Value(
                                    value=18,
                                    unit=Unit(
                                        reference='http://purl.obolibrary.org/obo/UO_0000032'))
                            ]
                        ),
                    ])
                )
            ],
            measurements=[
                Measurement(
                    type='FLOW',
                    block=BlockReference(label='experiment'),
                    controls=[
                        Control(
                            name='positive_gfp',
                            sample=Sample(
                                subject=SubjectReference(
                                    entity_name='MG1655_NAND_Circuit'),
                                treatments=[
                                    TreatmentReference.create_from(treatment_name='timepoint', value=Value(
                                        value=18, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000032'))),
                                    TreatmentReference.create_from(treatment_name='IPTG', attribute='concentration', value=Value(
                                        value=0, unit=Unit(reference='http://purl.obolibrary.org/obo/UO_0000064')))
                                ]
                            )
                        ),
                        Control(
                            name='negative_gfp',
                            sample=Sample(subject=SubjectReference(
                                entity_name='MG1655_empty_landing_pads'))
                        )
                    ],
                    performers=['Ginkgo']
                )
            ]
        )
        r_json = json.dumps(r1, cls=ExperimentEncoder)
        r2 = json.loads(r_json, cls=ExperimentDecoder)
        assert r1 == r2
